---
title: "Assignment LHS"
author: "Connor Flynn"
date: "4/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(patchwork)
library(purrr)
library(pse)
```


```{r}
source(here("atm_conduct_function.R"))
```


```{r}
#atm_conduct(vm = 20, zm = 100, h = 10)

atm_conduct(vm = 20, h = 10)
```

## Question 2:
```{r}
#parameters
factors = c("vm", "h")

#how many parameter sets to run
nsets = 100

#choose distributions for parameters
q = c("qnorm", "qunif")
q.arg = list(list(mean = 250, sd = 30), 
             list(min = 950, max = 1050)
             )

#generate samples from LHS
sens_conduct = LHS(NULL, factors, nsets, q, q.arg)
sens_pars = get.data(sens_conduct)
head(sens_pars)
```

```{r}
#run model for all of the parameters generated by LHS, using pmap

conductance <- sens_pars %>% 
  pmap(atm_conduct)

# turn results in to a dataframe for easy display/analysis
conductance_df = conductance %>% map_dfr(`[`,c("Cat"))

mean(conductance_df$Cat)
```


## Question 3: 
```{r}
kd <- 0.7
k0 <- 0.1
deviation <- 0.01
# 
# wind_speed_distribution = rnorm(mean = 250,
#               sd = 30,
#               n = nsamples)
# 
# veg_height <- runif(min = 950,
#               max = 1050,
#               n = nsamples)
# 
# kd_dist <- runif(min = kd-deviation*kd,
#               max = kd+deviation*kd, 
#               n = 22)
#   
# k0_dist <- runif(min = k0-deviation*k0,
#               max = k0+deviation*k0, 
#               n = 22)
```

### Part a:
```{r}
#parameters
factors = c("kd", "k0", "vm", "h")

#how many parameter sets to run
nsets = 100

#choose distributions for parameters
q = c("qunif", "qunif", "qnorm", "qunif")
q.arg = list(list(min = kd-deviation*kd, 
                  max = kd+deviation*kd),
             list(min = k0-deviation*k0,
                  max = k0+deviation*k0),
             list(mean = 250, sd = 30), 
             list(min = 950, max = 1050)
             )

#generate samples from LHS
sens_conduct = LHS(NULL, factors, nsets, q, q.arg)
sens_pars = get.data(sens_conduct)
head(sens_pars)
```

### Part b:
```{r}
#run model for all of the parameters generated by LHS, using pmap

conductance <- sens_pars %>% 
  pmap(atm_conduct)

head(conductance)
```

```{r}
# turn results in to a dataframe for easy display/analysis
conductance_df = conductance %>% map_dfr(`[`,c("Cat"))
```

```{r}
sens_conduct = pse::tell(sens_conduct, t(as.matrix(conductance_df)),
                        res.names=c("Cat"))
```

### Part c:
```{r}
# Plot conductance estimates accounting for parameter uncertainty

ggplot(conductance_df, aes(x=factor(0), y=Cat))+
  geom_boxplot()+
  labs(y="Atmospheric Conductance",
       x = NULL,
       title = "Atmospheric Conductance Range")+
  theme_bw()+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        plot.title = element_text(hjust = 0.5))
```

### Part d:
```{r}
#Plot conductance estimates against each parameter

# now we use built in LHS functions to analyze parameter sensitivity
pse::plotscatter(sens_conduct, col="blue", cex=5)
```

### Part e:
```{r}
# estimate the Partial Rank Correlation Coefficients
pse::plotprcc(sens_conduct)
sens_conduct$prcc
```

### Part f:
When analyzing parameter sensitivity, our results indicate that wind speed is the greatest indicator of aerodynamic conductance. Thus, to reduce uncertainty in aerodymaic conductance estimates, one should focus on wind speed.
